---
project_name: hello-container

before:
  hooks:
  - go mod tidy

builds:
- main: ./cmd/hello/
  binary: hello
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  ignore:
  - goos: windows
    goarch: arm
  - goos: windows
    goarch: arm64

archives:
- replacements:
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - typo

dockers:
- dockerfile: Dockerfile
  goos: linux
  goarch: amd64
  binaries:
  - hello
  image_templates:
  - "billglover/{{.ProjectName}}:latest"
  - "billglover/{{.ProjectName}}:{{ .Tag }}"

release:
  prerelease: auto